name: katolika
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  sqflite: ^2.3.0
  smooth_page_indicator: ^1.1.0
  flutter_onboarding_slider: ^1.0.11
  webview_flutter: ^4.4.3
  path_provider: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  share_plus: ^7.2.1
  path: ^1.8.3
  intl: ^0.19.0
  screenshot: ^2.1.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/olomasina/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/katolika.db

fonts:
    - family: Cursif
      fonts:
        - asset: fonts/Cursif/Cursif.ttf
    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento/Sacramento-Regular.ttf